In [1]:
import numpy as np

In [2]:
list1 = ["A", "B", "C"]

In [4]:
nplist1D = np.array(list1)

In [5]:
print(nplist1D)

['A' 'B' 'C']


In [12]:
liste2 = [["1", "4", 15],[5, 3, 4], [66, 77, 88]]
nplist2D = np.array(liste2)
print(nplist2D)

[['1' '4' '15']
 ['5' '3' '4']
 ['66' '77' '88']]


In [13]:
type(nplist2D[0][0])

numpy.str_

In [15]:
print(np.sort([5, 2, 6, 10, 0, 6], False))

[ 0  2  5  6  6 10]


In [30]:
arr = np.array([[8, 3, 2],
               [3, 6, 5],
               [6, 1, 4]])
print(arr)

[[8 3 2]
 [3 6 5]
 [6 1 4]]


In [22]:
arr = np.sort(arr,
       order=['f0'],
       axis=0).view(int)

In [24]:
arr.view('i8,i8,i8')

NameError: name 'view' is not defined

In [26]:
print(arr.view())

[[3 6 5]
 [6 1 4]
 [8 3 2]]


In [29]:
arr[::-1]

[8, 6, 4, 2]

In [28]:
arr = [2, 4, 6, 8]

In [32]:
arr.shape

(3, 3)

In [34]:
import random as rd

In [43]:
print([rd.randrange(5) for i in range(10)])

[2, 1, 0, 3, 1, 1, 0, 2, 0, 1]


In [44]:
"abcds111".isalnum()

True

In [45]:
check_unique(* arr):
    uniq = set(arr)
    uniq.re
    return len()

SyntaxError: invalid syntax (4286990971.py, line 1)

In [54]:
phrase = "blabla car sitebLLabla "
keys = {}
for s in phrase:
    if s not in keys:
        keys[s] = 1
    else:
        keys[s] +=1
print(keys)

{'b': 4, 'l': 3, 'a': 5, ' ': 3, 'c': 1, 'r': 1, 's': 1, 'i': 1, 't': 1, 'e': 1, 'L': 2}


In [55]:
import collections

In [57]:
collections.Counter(phrase)

Counter({'b': 4,
         'l': 3,
         'a': 5,
         ' ': 3,
         'c': 1,
         'r': 1,
         's': 1,
         'i': 1,
         't': 1,
         'e': 1,
         'L': 2})

In [59]:
def print_pairs(arr, N):
   # hash set
   hash_set = set()
    
   for i in range(0, len(arr)):
       val = N-arr[i]
       if (val in hash_set):    #check if N-x is there in set, print the pair
           print("Pairs " + str(arr[i]) + ", " + str(val))
       hash_set.add(arr[i])

# driver code
arr = [1, 2, 40, 3, 9, 4]
N = 3
print_pairs(arr, N)


Pairs 2, 1


In [147]:
def maxPower(s) :
        max = 1
        l = ''
        lg = len(s)
        lmax =0
        for i in range(lg-1):
            print("-----------", i)
            if s[i] == s[i+1]:
                l = s[i]
                lmax +=1
                print("lmax : ", lmax)
            else:
                lmax = 1
                l = s[i+1]
            if lmax > max:
                max = lmax
        return max
                


In [148]:
print(maxPower("leetcode"))

----------- 0
----------- 1
lmax :  2
----------- 2
----------- 3
----------- 4
----------- 5
----------- 6
2


In [149]:
def maxPower2(s: str) -> int:
        count = 0
        max_count = 0
        previous = None
        for c in s:
            if c == previous:
                # if same as previous one, increase the count
                count += 1
            else:
                # else, reset the count
                previous = c
                count = 1
            max_count = max(max_count, count)
        return max_count

In [150]:
print(maxPower2("leetcode"))

2


In [151]:
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

In [158]:
def addTwoNumbers(ListNode: list1, ListNode: list2):
    l1 = len(list1)
    l2 = len(list2)
    ng = max(l1, l2)
    list3 = []
    for i in range(lg):
        list1.val + list.val
        
    

IndentationError: expected an indented block (65749679.py, line 6)

In [159]:
# Definition for singly-linked list.
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next


In [ ]:
class Solution:
    def addTwoNumbers(self, l1: ListNode, l2: ListNode )-> ListNode:
        if l1 == None:
            return l2
        if l2 == None:
            return l1
        
        if l1.val + l2.val < 10:
            newNode = ListNode(l1.val + l2.val)
            newNode.next = nodeself.addTwoNumbers(l1.next, l2.next)
        else:
            newNode = ListNode((l1.val + l2.val)% 10)
            newNode.next = self.addTwoNumbers(newNode(1), self.addTwoNumbers(l1.next, l2.next))
        
        return newNode
